### ISSUE TITLE
Redesign the website using tailwindcss | React Js 

### ISSUE THREAD

**Issue by amir-mansoor** [amir-mansoor/recipe-reacts#1]
this is a simple issue create a design for the website however you want but make it clean. The website have 4 pages. just make a simple design for each page using tailwind css. 
submit screenshots with pull request otherwise the code will not be reviewed.

**Comment by GULSHANITSYOU** [comment]
Hi Amir 
I want work on it could you please assign it to me .

**Comment by amir-mansoor** [comment]
Hey Kumar! let me know if you want to work on this issue

**Comment by ghost** [comment]
i want to contribute to this project

**Comment by amir-mansoor** [comment]
hey Avinash! Ok i assign this issue to you

**Comment by ghost** [comment]
ok can you sent me photos how you want design it will boost you work
i have forked and i will start working in this

**Comment by amir-mansoor** [comment]
Don't think about the design too much. Make a design however you want but make decent.

**Comment by ghost** [comment]
> Don't think about the design too much. Make a design however you want but make decent.

ok Then lets go

**Comment by ghost** [comment]
this is the first image about about how the design will go in your code 
![aboutUS](https://github.com/amir-mansoor/recipe-reacts/assets/168642842/07e6507d-e546-4af1-b402-c05ceb2a8edd)
Tell me If you want changes if you like this i will make all pages in this way design

**Comment by amir-mansoor** [comment]
Sorry for the late replay. i was busy!. 
Yah this one is awesome.

**Comment by ghost** [comment]
np problem 

> Sorry for the late replay. i was busy!. Yah this one is awesome.

no Problem Soon i will send you all converted Pages With proper Presentation
