### ISSUE TITLE
search recipies using Reactjs |

### ISSUE THREAD

**Issue by amir-mansoor** [amir-mansoor/recipe-reacts#2]
create an input on home page and search recipies in redux store. if the the recipes were found then show the recipies cards if not then show the msg that "No recipies found"

**Comment by VaibhavSahu19** [comment]
Hi,
I would like to implement this.
Can you please guide me on how to do this professionally as this is my first time contributing to open source project.
Thanks

**Comment by amir-mansoor** [comment]
create a new branch in your clone repo.
git checkout -b branchname 
then implement the feature
After adding the feature
enter these commands.
git add .
git commit -m "meaning full message"
git push origin whatever the branch name
then go to fork repository on github.
it will show some kind of message on top.
like a pull request click on that and follow the steps.

**Comment by VaibhavSahu19** [comment]
Okay, thanks
I am on it

**Comment by VaibhavSahu19** [comment]
remote: Permission to amir-mansoor/recipe-reacts.git denied to VaibhavSahu19
I followed the same steps as you suggested. 
<img width="641" alt="Screenshot 2024-06-24 164040" src="https://github.com/amir-mansoor/recipe-reacts/assets/108462336/0c0a15a9-cb14-4cf6-8cf4-62a062d5a83a">

**Comment by amir-mansoor** [comment]
How did you clone the repository

**Comment by VaibhavSahu19** [comment]
git clone "https link from the code dropdown"

**Comment by amir-mansoor** [comment]
Did you clone it from your github account or from my account.
this is first time i am seeing this kind of error. 
create a fork from my repo then clone the repo from your github account.
