### ISSUE TITLE
Header is showing two times on Home page | React Js

### ISSUE THREAD

**Issue by amir-mansoor** [amir-mansoor/recipe-reacts#4]
the header is showing two times on page. figure out the issue

**Comment by VaibhavSahu19** [comment]
Hi,
Actually I don't see any such issue in my local machine.......
<img width="935" alt="Screenshot 2024-06-27 194515" src="https://github.com/amir-mansoor/recipe-reacts/assets/108462336/675aae82-39bf-4627-b755-4a36da776b3d">

**Comment by VaibhavSahu19** [comment]
Can you please provide me more details about the problem?

**Comment by amir-mansoor** [comment]
I clone the repo again and run these commands 
npm i 
npm run dev
when the page was open 
!
![Screenshot 2024-06-28 at 09-46-36 Vite React](https://github.com/amir-mansoor/recipe-reacts/assets/69566729/6ca0253d-25ad-41c9-b2ef-b75c0f30855b)
